import './globals.css';

import { Indie_Flower } from 'next/font/google'

const indie = Indie_Flower({
  weight: '400',
  subsets: ['latin'],
  variable: '--indie'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={indie.variable}>{children}</body>
    </html>
  )
}
